#!/bin/bash
# Agent start script — runs every time the container starts.
#
# Handles per-start setup: shell profile, agent environment.
# Called by agent-entrypoint.sh on every container start.
#
# Environment (set by entrypoint):
#   AGENT_NUM      — agent number (1-N)
#   AGENT_SUFFIX   — agent suffix (agent01, agent02, etc.)
#   PROJECT_NAME   — project name (set by igor)

set -euo pipefail

log_info()    { echo "[START] $*"; }
log_success() { echo "[OK]    $*"; }
log_warn()    { echo "[WARN]  $*" >&2; }

log_info "Starting agent ${AGENT_NUM:-?}..."

# Ensure USER is set.
export USER="${USER:-$(whoami)}"

# ============================================================================
# Shell Profile Setup
# ============================================================================
# Add agent environment to bashrc.d if the directory exists.
PROFILE_DIR="/etc/bashrc.d"
if [[ -d "$PROFILE_DIR" ]] && [[ -w "$PROFILE_DIR" ]]; then
    AGENT_PROFILE="${PROFILE_DIR}/90-agent.sh"
    cat > "${AGENT_PROFILE}" << EOF
#!/bin/bash
# Agent environment — auto-generated by agent-start.sh
export AGENT_NUM="${AGENT_NUM:-}"
export AGENT_SUFFIX="${AGENT_SUFFIX:-}"
export PROJECT_NAME="${PROJECT_NAME:-}"
EOF
    chmod +x "${AGENT_PROFILE}"
    log_success "Created agent shell profile"
elif [[ -d "$PROFILE_DIR" ]]; then
    # Try with sudo if available.
    if command -v sudo &>/dev/null; then
        sudo tee "${PROFILE_DIR}/90-agent.sh" > /dev/null << EOF
#!/bin/bash
export AGENT_NUM="${AGENT_NUM:-}"
export AGENT_SUFFIX="${AGENT_SUFFIX:-}"
export PROJECT_NAME="${PROJECT_NAME:-}"
EOF
        sudo chmod +x "${PROFILE_DIR}/90-agent.sh"
        log_success "Created agent shell profile (via sudo)"
    fi
fi

log_success "Agent ${AGENT_NUM:-?} per-start setup complete"
