# GitHub Actions Workflow: Build and Test Containers
#
# This workflow builds and tests container images on pushes and pull requests.
# Customize this template for your project by:
# 1. Updating the container variants in the matrix
# 2. Modifying build arguments for your features
# 3. Adjusting test commands for your test suite
#
# Documentation: https://docs.github.com/en/actions

name: Build and Test

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allow manual triggering

# Environment variables available to all jobs
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  # =====================================
  # Unit Tests (no Docker required)
  # =====================================
  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run unit tests
        run: |
          echo "Running unit tests..."
          export SKIP_DOCKER_CHECK=true
          ./tests/run_unit_tests.sh

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-results
          path: tests/results/
          retention-days: 7

  # =====================================
  # Code Quality Checks
  # =====================================
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Full history for better analysis

      - name: Run shellcheck
        run: |
          sudo apt-get update && sudo apt-get install -y shellcheck

          # Check all shell scripts
          FAILED=0
          while IFS= read -r file; do
            echo "Checking $file..."
            if ! shellcheck --severity=warning "$file"; then
              FAILED=1
            fi
          done < <(git ls-files '*.sh' '*.bash')

          if [ $FAILED -eq 1 ]; then
            echo "❌ Shellcheck found issues"
            exit 1
          fi

          echo "✅ All scripts passed shellcheck"

      - name: Secret scanning
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # =====================================
  # Build Container Images
  # =====================================
  build:
    name: Build ${{ matrix.variant.name }}
    runs-on: ubuntu-latest
    needs: [unit-test, code-quality]
    permissions:
      contents: read
      packages: write # Required to push to GHCR
    strategy:
      # Don't cancel other builds if one fails
      fail-fast: false
      matrix:
        variant:
          # Customize these variants for your project
          - name: minimal
            build_args: |
              PROJECT_NAME=myproject
              PROJECT_PATH=.

          - name: python-dev
            build_args: |
              PROJECT_NAME=myproject
              PROJECT_PATH=.
              INCLUDE_PYTHON_DEV=true
              INCLUDE_DEV_TOOLS=true
              INCLUDE_DOCKER=true

          - name: node-dev
            build_args: |
              PROJECT_NAME=myproject
              PROJECT_PATH=.
              INCLUDE_NODE_DEV=true
              INCLUDE_DEV_TOOLS=true
              INCLUDE_DOCKER=true

          # Add more variants as needed...

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            # branch-variant (e.g., main-python-dev)
            type=ref,event=branch,suffix=-${{ matrix.variant.name }}
            # tag-variant (e.g., v1.0.0-python-dev)
            type=ref,event=tag,suffix=-${{ matrix.variant.name }}
            # pr-123-variant (for pull requests)
            type=ref,event=pr,suffix=-${{ matrix.variant.name }}
            # variant-latest (only on main branch)
            type=raw,value=${{ matrix.variant.name }}-latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: ${{ matrix.variant.build_args }}
          # Use GitHub Actions cache for faster builds
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # =====================================
  # Integration Tests
  # =====================================
  integration-test:
    name: Test ${{ matrix.variant.name }}
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: read # Required to pull from GHCR
    strategy:
      fail-fast: false
      matrix:
        variant:
          - name: minimal
            test: minimal
          - name: python-dev
            test: python_dev
          - name: node-dev
            test: node_dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull and test image
        run: |
          # Sanitize branch name (replace / with -)
          TAG_NAME="${{ github.ref_name }}"
          TAG_NAME="${TAG_NAME//\//-}"
          IMAGE="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${TAG_NAME}-${{ matrix.variant.name }}"

          echo "Pulling image: $IMAGE"
          docker pull "$IMAGE"

          echo "Running integration tests..."
          IMAGE_TO_TEST="$IMAGE" ./tests/run_integration_tests.sh ${{ matrix.variant.test }}

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: integration-test-${{ matrix.variant.name }}
          path: tests/results/
          retention-days: 7

  # =====================================
  # Security Scanning
  # =====================================
  security-scan:
    name: Security Scan ${{ matrix.variant }}
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' # Only on push, not PRs
    permissions:
      contents: read
      packages: read
      security-events: write # Required for SARIF upload
    strategy:
      matrix:
        variant: [minimal, python-dev, node-dev]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare image tag
        id: tag
        run: |
          TAG_NAME="${{ github.ref_name }}"
          TAG_NAME="${TAG_NAME//\//-}"
          echo "sanitized=$TAG_NAME" >> $GITHUB_OUTPUT

      - name: Pull image
        run: |
          docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.sanitized }}-${{ matrix.variant }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.sanitized }}-${{ matrix.variant }}
          format: "sarif"
          output: "trivy-results-${{ matrix.variant }}.sarif"
          severity: "CRITICAL,HIGH"

      - name: Upload to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: "trivy-results-${{ matrix.variant }}.sarif"
          category: "container-${{ matrix.variant }}"

      - name: Print vulnerability summary
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.sanitized }}-${{ matrix.variant }}
          format: "table"
          severity: "CRITICAL,HIGH,MEDIUM"
