# yamllint configuration
# https://yamllint.readthedocs.io/en/stable/configuration.html

extends: default

rules:
  # Line length - allow longer lines for readability
  line-length:
    max: 120
    level: warning

  # Indentation - 2 spaces
  indentation:
    spaces: 2
    indent-sequences: true

  # Comments - require space after #
  comments:
    min-spaces-from-content: 1

  # Comments indentation - disable due to false positives
  # (comments at service level after nested content)
  comments-indentation: disable

  # Document start (---) - not required for all files
  document-start:
    present: false

  # Truthy values - allow yes/no/on/off
  truthy:
    allowed-values: ["true", "false", "yes", "no", "on", "off"]
    check-keys: false

  # Trailing spaces - error
  trailing-spaces: enable

  # Empty lines - reasonable limits
  empty-lines:
    max: 2

  # Brackets - consistent spacing
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1

  # Braces - consistent spacing
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1

# Ignore patterns
ignore: |
  .git/
  node_modules/
  vendor/
  .github/
