# Kubernetes Example: AWS Secrets Manager with IRSA
#
# This example demonstrates using AWS Secrets Manager with IAM Roles for
# Service Accounts (IRSA) on Amazon EKS.
#
# Prerequisites:
#   1. EKS cluster with OIDC provider configured
#   2. IAM role with secretsmanager:GetSecretValue permission
#   3. Secret created in AWS Secrets Manager
#
# Setup:
#   # Create IAM policy
#   aws iam create-policy \
#     --policy-name myapp-secrets-policy \
#     --policy-document '{
#       "Version": "2012-10-17",
#       "Statement": [{
#         "Effect": "Allow",
#         "Action": "secretsmanager:GetSecretValue",
#         "Resource": "arn:aws:secretsmanager:us-east-1:123456789012:secret:myapp/*"
#       }]
#     }'
#
#   # Create IAM role for service account
#   eksctl create iamserviceaccount \
#     --name myapp \
#     --namespace default \
#     --cluster my-cluster \
#     --attach-policy-arn arn:aws:iam::123456789012:policy/myapp-secrets-policy \
#     --approve

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: myapp
  namespace: default
  annotations:
    # IRSA annotation - role created by eksctl or manually
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/myapp-secrets-role

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-aws-config
  namespace: default
data:
  AWS_SECRET_NAME: "myapp/production/secrets"
  AWS_REGION: "us-east-1"
  AWS_SECRET_PREFIX: "APP_"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      serviceAccountName: myapp
      containers:
        - name: app
          image: myapp:latest
          env:
            # Enable AWS Secrets Manager integration
            - name: AWS_SECRETS_ENABLED
              value: "true"

            # Universal loader configuration
            - name: SECRET_LOADER_ENABLED
              value: "true"
            - name: SECRET_LOADER_PRIORITY
              value: "aws"
            - name: SECRET_LOADER_FAIL_ON_ERROR
              value: "true"

          # AWS configuration from ConfigMap
          envFrom:
            - configMapRef:
                name: myapp-aws-config

          ports:
            - containerPort: 8080
              name: http

          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
