# Kubernetes Example: GCP Secret Manager with Workload Identity
#
# This example demonstrates using GCP Secret Manager with Workload Identity
# on Google Kubernetes Engine (GKE).
#
# Prerequisites:
#   1. GKE cluster with Workload Identity enabled
#   2. GCP project with Secret Manager API enabled
#   3. Secrets created in Secret Manager
#
# Setup:
#   # Enable Workload Identity on cluster
#   gcloud container clusters update CLUSTER_NAME \
#     --workload-pool=PROJECT_ID.svc.id.goog
#
#   # Create secrets in Secret Manager
#   echo -n "super-secret" | gcloud secrets create db-password --data-file=-
#   echo -n "api-key-value" | gcloud secrets create api-key --data-file=-
#
#   # Create GCP service account
#   gcloud iam service-accounts create myapp-secrets \
#     --project=PROJECT_ID
#
#   # Grant Secret Manager permissions
#   gcloud projects add-iam-policy-binding PROJECT_ID \
#     --member="serviceAccount:SA_NAME@YOUR_PROJECT_ID.iam.gserviceaccount.com" \
#     --role="roles/secretmanager.secretAccessor"
#
#   # Bind Kubernetes SA to GCP SA (Workload Identity)
#   gcloud iam service-accounts add-iam-policy-binding \
#     SA_NAME@YOUR_PROJECT_ID.iam.gserviceaccount.com \
#     --role=roles/iam.workloadIdentityUser \
#     --member="serviceAccount:YOUR_PROJECT_ID.svc.id.goog[default/myapp]"

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: myapp
  namespace: default
  annotations:
    # Bind to GCP service account via Workload Identity
    iam.gke.io/gcp-service-account: SA_NAME@YOUR_PROJECT_ID.iam.gserviceaccount.com

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-gcp-config
  namespace: default
data:
  GCP_PROJECT_ID: "YOUR_PROJECT_ID" # Replace with your project ID
  GCP_SECRET_NAMES: "db-password,api-key,encryption-key"
  GCP_SECRET_PREFIX: "APP_"
  GCP_SECRET_VERSION: "latest"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      serviceAccountName: myapp
      containers:
        - name: app
          image: myapp:latest
          env:
            # Enable GCP Secret Manager integration
            - name: GCP_SECRETS_ENABLED
              value: "true"

            # Universal loader configuration
            - name: SECRET_LOADER_ENABLED
              value: "true"
            - name: SECRET_LOADER_PRIORITY
              value: "gcp"
            - name: SECRET_LOADER_FAIL_ON_ERROR
              value: "true"

          # GCP configuration from ConfigMap
          envFrom:
            - configMapRef:
                name: myapp-gcp-config

          ports:
            - containerPort: 8080
              name: http

          # Health checks
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5

          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"

---
# Alternative: Using external-secrets operator
# More flexible approach that syncs GCP secrets to Kubernetes secrets
#
# apiVersion: external-secrets.io/v1beta1
# kind: SecretStore
# metadata:
#   name: gcp-backend
#   namespace: default
# spec:
#   provider:
#     gcpsm:
#       projectID: "PROJECT_ID"
#       auth:
#         workloadIdentity:
#           clusterLocation: us-central1
#           clusterName: my-cluster
#           serviceAccountRef:
#             name: myapp
# ---
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: myapp-secrets
#   namespace: default
# spec:
#   refreshInterval: 1h
#   secretStoreRef:
#     name: gcp-backend
#     kind: SecretStore
#   target:
#     name: myapp-secrets
#     creationPolicy: Owner
#   data:
#   - secretKey: database-password
#     remoteRef:
#       key: db-password
#   - secretKey: api-key
#     remoteRef:
#       key: api-key
