# Kubernetes Example: HashiCorp Vault Integration
#
# This example demonstrates using Vault with Kubernetes service account authentication.
# Requires Vault Kubernetes auth method to be configured.
#
# Prerequisites:
#   1. Vault server with Kubernetes auth method enabled
#   2. Vault policy granting access to secrets
#   3. Kubernetes service account with Vault role binding
#
# Setup:
#   # Enable Kubernetes auth in Vault
#   vault auth enable kubernetes
#
#   # Configure Kubernetes auth
#   vault write auth/kubernetes/config \
#     kubernetes_host="https://kubernetes.default.svc:443"
#
#   # Create policy
#   vault policy write myapp - <<EOF
#   path "secret/data/myapp/*" {
#     capabilities = ["read"]
#   }
#   EOF
#
#   # Create role
#   vault write auth/kubernetes/role/myapp-role \
#     bound_service_account_names=myapp \
#     bound_service_account_namespaces=default \
#     policies=myapp \
#     ttl=24h

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: myapp
  namespace: default

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-vault-config
  namespace: default
data:
  VAULT_ADDR: "https://vault.vault.svc.cluster.local:8200"
  VAULT_AUTH_METHOD: "kubernetes"
  VAULT_K8S_ROLE: "myapp-role"
  VAULT_SECRET_PATH: "secret/data/myapp/production"
  VAULT_SECRET_PREFIX: "APP_"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      serviceAccountName: myapp
      containers:
      - name: app
        image: myapp:latest
        env:
        # Enable Vault integration
        - name: VAULT_ENABLED
          value: "true"

        # Universal loader configuration
        - name: SECRET_LOADER_ENABLED
          value: "true"
        - name: SECRET_LOADER_PRIORITY
          value: "vault"
        - name: SECRET_LOADER_FAIL_ON_ERROR
          value: "true"

        # Vault configuration from ConfigMap
        envFrom:
        - configMapRef:
            name: myapp-vault-config

        ports:
        - containerPort: 8080
          name: http

        # Health checks
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10

        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5

        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
